# Docker Compose for Home Assistant Addon Development
# Simplified configuration for addon testing and development

version: '3.8'

services:
  # Printernizer as Home Assistant Addon
  printernizer-addon:
    build:
      context: .
      dockerfile: homeassistant/addon/Dockerfile
    container_name: printernizer-addon-dev
    hostname: printernizer-addon
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - ENVIRONMENT=homeassistant
      - LOG_LEVEL=debug
      - DATABASE_PATH=/data/printernizer.db
      - ENABLE_WEBSOCKETS=true
      - PRINTER_POLLING_INTERVAL=30
      - MAX_CONCURRENT_DOWNLOADS=5
      - ENABLE_GERMAN_COMPLIANCE=true
      - VAT_RATE=19.0
      - CURRENCY=EUR
      # Home Assistant Supervisor API (simulated)
      - SUPERVISOR_TOKEN=dev_token_here
    volumes:
      - printernizer-addon-data:/data
      - printernizer-addon-share:/share
      - printernizer-addon-ssl:/ssl
      - ./config:/tmp/addon_config
    ports:
      - "8000:8000"
    networks:
      - homeassistant-addon
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Mock MQTT Broker (like Home Assistant's)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: ha-mqtt-broker
    hostname: mqtt-broker
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - homeassistant-addon
    command: mosquitto -c /mosquitto/config/mosquitto.conf

networks:
  homeassistant-addon:
    driver: bridge
    name: homeassistant-addon

volumes:
  printernizer-addon-data:
    name: printernizer-addon-data
    driver: local
  printernizer-addon-share:
    name: printernizer-addon-share  
    driver: local
  printernizer-addon-ssl:
    name: printernizer-addon-ssl
    driver: local
  mosquitto-config:
    name: ha-mosquitto-config
    driver: local
  mosquitto-data:
    name: ha-mosquitto-data
    driver: local
  mosquitto-log:
    name: ha-mosquitto-log
    driver: local