# Printernizer Printer API Credentials Management
# Secure credential storage and management for Milestone 1.2

# Sealed Secrets for Production Printer Credentials
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bambu-printer-credentials
  namespace: printernizer
spec:
  encryptedData:
    # Base64 encoded and sealed printer credentials
    # Generate using: echo -n "actual-access-code" | kubeseal --raw --from-file=/dev/stdin --name bambu-printer-credentials --namespace printernizer
    bambu_a1_ip: "AgBy..." # Sealed IP address
    bambu_a1_access_code: "AgBy..." # Sealed access code
    bambu_a1_serial: "AgBy..." # Sealed serial number
  template:
    metadata:
      name: bambu-printer-credentials
      namespace: printernizer
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prusa-printer-credentials
  namespace: printernizer
spec:
  encryptedData:
    # Prusa PrusaLink API credentials
    prusa_core_one_ip: "AgBy..." # Sealed IP address
    prusa_core_one_api_key: "AgBy..." # Sealed API key
    prusa_core_one_hostname: "AgBy..." # Sealed hostname
  template:
    metadata:
      name: prusa-printer-credentials
      namespace: printernizer
    type: Opaque

---
# RBAC for Printer Credential Access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: printernizer-printer-access
  namespace: printernizer
  labels:
    app: printernizer
    component: printer-access

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: printer-credentials-reader
  namespace: printernizer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["bambu-printer-credentials", "prusa-printer-credentials"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: printernizer-printer-access-binding
  namespace: printernizer
subjects:
- kind: ServiceAccount
  name: printernizer-printer-access
  namespace: printernizer
roleRef:
  kind: Role
  name: printer-credentials-reader
  apiGroup: rbac.authorization.k8s.io

---
# Network Policy for Printer Communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: printer-network-access
  namespace: printernizer
spec:
  podSelector:
    matchLabels:
      app: printernizer-backend
  policyTypes:
  - Egress
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  
  # Allow HTTPS/HTTP for general internet access
  - to: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  
  # Allow specific printer IP ranges (adjust based on your network)
  - to:
    - ipBlock:
        cidr: 192.168.1.0/24  # Local network range for printers
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8      # Private network ranges
  - to:
    - ipBlock:
        cidr: 172.16.0.0/12
  
  # MQTT for Bambu Lab (port 8883 for secure MQTT)
  - ports:
    - protocol: TCP
      port: 8883
  
  # HTTP API for Prusa (typically port 80/443)
  - ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443

---
# Security Context for Printer Access Pods
apiVersion: v1
kind: SecurityContext
metadata:
  name: printer-security-context
spec:
  # Run as non-root user
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  
  # Security capabilities
  seccompProfile:
    type: RuntimeDefault
  
  # Read-only root filesystem
  readOnlyRootFilesystem: true
  
  # No privilege escalation
  allowPrivilegeEscalation: false
  
  # Drop all capabilities
  capabilities:
    drop:
    - ALL
    add:
    - NET_BIND_SERVICE  # Only if needed for specific ports

---
# Pod Security Policy for Printer Access
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: printer-access-psp
  namespace: printernizer
spec:
  privileged: false
  allowPrivilegeEscalation: false
  
  # Required to prevent escalations to root
  requiredDropCapabilities:
    - ALL
  
  # Allow core volume types
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  
  # Require the container to run without root privileges
  runAsUser:
    rule: 'MustRunAsNonRoot'
  
  # This policy assumes the nodes are using AppArmor rather than SELinux
  seLinux:
    rule: 'RunAsAny'
  
  # Forbid adding the root group to the list of groups a container can run as
  fsGroup:
    rule: 'RunAsAny'

---
# ConfigMap for Printer Security Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: printer-security-config
  namespace: printernizer
data:
  # Connection security settings
  connection_timeout: "30"
  max_retry_attempts: "3"
  retry_backoff_seconds: "5"
  
  # TLS/SSL settings for printer communication
  verify_ssl: "true"
  tls_version: "1.2"
  
  # Rate limiting for printer API calls
  max_requests_per_minute: "60"
  burst_limit: "10"
  
  # Connection pooling settings
  max_connections_per_printer: "5"
  connection_pool_timeout: "60"
  
  # Audit logging
  audit_printer_connections: "true"
  log_credential_access: "true"  # Log access events, not credentials
  
  # German GDPR compliance settings
  gdpr_enabled: "true"
  data_retention_days: "2555"  # 7 years for German business compliance
  anonymize_ip_addresses: "true"
  
  # Encryption settings for sensitive data
  encrypt_printer_data: "true"
  encryption_key_rotation_days: "90"

---
# Vault Integration (if using HashiCorp Vault)
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: printernizer-printer-secrets
  namespace: printernizer
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.porcus3d.internal:8200"
    roleName: "printernizer-printer-access"
    objects: |
      - objectName: "bambu_a1_credentials"
        secretPath: "secret/data/printers/bambu/a1"
        secretKey: "credentials"
      - objectName: "prusa_core_one_credentials"
        secretPath: "secret/data/printers/prusa/core-one"
        secretKey: "credentials"
  secretObjects:
  - data:
    - key: bambu_a1_credentials
      objectName: bambu_a1_credentials
    - key: prusa_core_one_credentials
      objectName: prusa_core_one_credentials
    secretName: printer-vault-secrets
    type: Opaque

---
# Monitoring for Security Events
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-monitoring-config
  namespace: printernizer
data:
  security_events.yml: |
    # Security event definitions for printer access
    events:
      - name: unauthorized_printer_access
        description: "Unauthorized access attempt to printer API"
        severity: "high"
        action: "alert"
      
      - name: credential_rotation_due
        description: "Printer credentials are due for rotation"
        severity: "medium"
        action: "notify"
      
      - name: excessive_api_calls
        description: "Excessive API calls to printer detected"
        severity: "medium"
        action: "rate_limit"
      
      - name: connection_encryption_failure
        description: "Failed to establish encrypted connection to printer"
        severity: "high"
        action: "alert"
    
    # Alert thresholds
    thresholds:
      failed_auth_attempts: 5
      api_calls_per_minute: 100
      connection_timeout_seconds: 60