#!/usr/bin/with-contenv bashio
# Printernizer - Home Assistant Add-on Startup Script
# Handles configuration from Home Assistant and starts the application

set -e

# Colors for output
bashio::log.info "Starting Printernizer Home Assistant Add-on v2.0.10..."

# Read configuration from Home Assistant options
CONFIG_PATH="/data/options.json"

# Parse options with jq and bashio
LOG_LEVEL=$(bashio::config 'log_level' 'info')
TIMEZONE=$(bashio::config 'timezone' 'Europe/Berlin')
ENABLE_3D_PREVIEW=$(bashio::config 'enable_3d_preview' 'true')
ENABLE_WEBSOCKETS=$(bashio::config 'enable_websockets' 'true')
ENABLE_BUSINESS_REPORTS=$(bashio::config 'enable_business_reports' 'true')

bashio::log.info "Configuration loaded from Home Assistant"
bashio::log.info "  • Log Level: ${LOG_LEVEL}"
bashio::log.info "  • Timezone: ${TIMEZONE}"
bashio::log.info "  • 3D Preview: ${ENABLE_3D_PREVIEW}"
bashio::log.info "  • WebSockets: ${ENABLE_WEBSOCKETS}"
bashio::log.info "  • Business Reports: ${ENABLE_BUSINESS_REPORTS}"

# Set timezone
export TZ="${TIMEZONE}"
bashio::log.info "Timezone set to ${TZ}"

# Create necessary directories
bashio::log.info "Setting up directories..."
mkdir -p /data/printernizer
mkdir -p /data/printernizer/printer-files
mkdir -p /data/printernizer/preview-cache
mkdir -p /data/printernizer/backups
mkdir -p /app/logs
mkdir -p /app/temp

# Generate environment configuration
bashio::log.info "Generating application configuration..."
cat > /app/.env << EOF
# Generated by Home Assistant Add-on
ENVIRONMENT=production
DEPLOYMENT_MODE=homeassistant
HA_INGRESS=true

# Server configuration
HOST=0.0.0.0
PORT=8000

# Logging
LOG_LEVEL=${LOG_LEVEL}

# Timezone and locale
TIMEZONE=${TIMEZONE}
TZ=${TIMEZONE}

# Database
DATABASE_PATH=/data/printernizer/printernizer.db

# File paths (persistent storage in /data)
UPLOAD_PATH=/data/printernizer/printer-files
BACKUP_PATH=/data/printernizer/backups
CACHE_PATH=/data/printernizer/preview-cache

# CORS - Allow Ingress
CORS_ORIGINS=http://172.30.32.2,https://172.30.32.2

# Feature flags from HA configuration
ENABLE_3D_PREVIEW=${ENABLE_3D_PREVIEW}
ENABLE_WEBSOCKETS=${ENABLE_WEBSOCKETS}
ENABLE_BUSINESS_REPORTS=${ENABLE_BUSINESS_REPORTS}

# Printer settings
PRINTER_POLLING_INTERVAL=30
MAX_CONCURRENT_DOWNLOADS=5

# German business defaults
CURRENCY=EUR
VAT_RATE=0.19
BUSINESS_LOCATION=Home

# Security for Ingress
INGRESS_SECURITY=true
ALLOWED_IPS=172.30.32.2
EOF

bashio::log.info "Environment configuration created"

# Initialize database if it doesn't exist
DATABASE_PATH="/data/printernizer/printernizer.db"
if [ ! -f "$DATABASE_PATH" ]; then
    bashio::log.info "Initializing database..."
    if [ -f "/app/database_schema.sql" ]; then
        sqlite3 "$DATABASE_PATH" < /app/database_schema.sql
        bashio::log.info "Database initialized successfully"
    else
        bashio::log.warning "Database schema not found, will be created by application"
    fi
else
    bashio::log.info "Database already exists"
fi

# Parse and log printer configuration
PRINTER_COUNT=$(bashio::config 'printers | length' '0')
if [ "$PRINTER_COUNT" -gt 0 ]; then
    bashio::log.info "Found ${PRINTER_COUNT} printer(s) in configuration:"
    for i in $(seq 0 $((PRINTER_COUNT - 1))); do
        PRINTER_NAME=$(bashio::config "printers[${i}].name")
        PRINTER_TYPE=$(bashio::config "printers[${i}].type")
        PRINTER_IP=$(bashio::config "printers[${i}].ip_address")
        PRINTER_ENABLED=$(bashio::config "printers[${i}].enabled" "true")

        bashio::log.info "  • ${PRINTER_NAME} (${PRINTER_TYPE}) @ ${PRINTER_IP} - Enabled: ${PRINTER_ENABLED}"
    done
else
    bashio::log.warning "No printers configured. Add printers via the web interface."
fi

# Network connectivity check
bashio::log.info "Checking network connectivity..."
if ping -c 1 -W 2 8.8.8.8 &> /dev/null; then
    bashio::log.info "Network connectivity: OK"
else
    bashio::log.warning "Limited network connectivity - printer connections may fail"
fi

# Display startup information
bashio::log.info "======================================"
bashio::log.info "Printernizer Add-on Configuration Complete"
bashio::log.info "======================================"
bashio::log.info "Access via Home Assistant Ingress or:"
bashio::log.info "  Web Interface: http://[host]:8000"
bashio::log.info "  API Docs: http://[host]:8000/docs"
bashio::log.info "======================================"

# Start the application
bashio::log.info "Starting Printernizer application server..."
bashio::log.info "This may take a moment while services initialize..."
cd /app
exec python3 src/main.py
