"""Tests for the Printernizer Connect API (/api/v1/connect)."""
from unittest.mock import AsyncMock, MagicMock

import pytest
from fastapi.testclient import TestClient

from src.utils.dependencies import get_api_key_service, get_printer_service

VALID_KEY = {"id": "key1", "name": "Laptop",
             "created_at": "2026-09-06T00:00:00+00:00", "last_used_at": None}
AUTH = {"X-Api-Key": "pk_valid"}


@pytest.fixture
def key_service(test_app):
    stub = AsyncMock()
    stub.verify = AsyncMock(return_value=VALID_KEY)
    test_app.dependency_overrides[get_api_key_service] = lambda: stub
    yield stub
    test_app.dependency_overrides.pop(get_api_key_service, None)


@pytest.fixture
def printer_service(test_app):
    stub = MagicMock()
    stub.list_printers = AsyncMock(return_value=[])
    test_app.dependency_overrides[get_printer_service] = lambda: stub
    yield stub
    test_app.dependency_overrides.pop(get_printer_service, None)


@pytest.fixture
def client(test_app):
    return TestClient(test_app)


class TestConnectInfoAuth:
    def test_requires_an_api_key(self, client, key_service, printer_service):
        assert client.get("/api/v1/connect/info").status_code == 401

    def test_rejects_an_invalid_api_key(self, client, key_service, printer_service):
        key_service.verify.return_value = None
        response = client.get("/api/v1/connect/info",
                              headers={"X-Api-Key": "pk_wrong"})
        assert response.status_code == 401


class TestConnectInfo:
    def test_reports_server_and_minimum_connect_version(
        self, client, key_service, printer_service
    ):
        data = client.get("/api/v1/connect/info", headers=AUTH).json()["data"]
        assert data["server_version"]
        assert data["min_connect_version"] == "0.1.0"

    def test_reports_capabilities(self, client, key_service, printer_service):
        caps = client.get("/api/v1/connect/info",
                          headers=AUTH).json()["data"]["capabilities"]
        assert caps["exports"] is True
        assert caps["profiles"] is False   # M4
        assert caps["printhost"] is False  # M5

    def test_lists_printers(self, client, key_service, printer_service):
        printer = MagicMock()
        printer.id = "printer-1"
        printer.name = "Core One"
        printer.type = MagicMock(value="prusa_core")
        printer.is_active = True
        printer_service.list_printers.return_value = [printer]

        printers = client.get("/api/v1/connect/info",
                              headers=AUTH).json()["data"]["printers"]
        assert printers == [{
            "id": "printer-1", "name": "Core One",
            "type": "prusa_core", "is_active": True,
        }]

    def test_returns_empty_printer_list_when_none_configured(
        self, client, key_service, printer_service
    ):
        data = client.get("/api/v1/connect/info", headers=AUTH).json()["data"]
        assert data["printers"] == []


import io
import json

from src.utils.dependencies import get_file_service

# The real shape FileUploadService.upload_files puts in `uploaded_files`
# (src/services/file_upload_service.py). Keep this in sync with that method —
# a fixture that invents fields makes every assertion below vacuous.
UPLOAD_OK = {
    "uploaded_files": [{
        "file_id": "file-1",
        "filename": "benchy.gcode",
        "file_path": "/data/library/models/6f/1b/benchy.gcode",
        "file_size": 2841923,
        "file_type": "gcode",
        "checksum": "abc123",
    }],
    "failed_files": [],
    "total_count": 1, "success_count": 1, "failure_count": 0,
}


@pytest.fixture
def file_service(test_app):
    stub = MagicMock()
    stub.settings = MagicMock(enable_upload=True)
    stub.upload_files = AsyncMock(return_value=UPLOAD_OK)
    test_app.dependency_overrides[get_file_service] = lambda: stub
    yield stub
    test_app.dependency_overrides.pop(get_file_service, None)


def _gcode(name="benchy.gcode"):
    return {"file": (name, io.BytesIO(b"; generated by PrusaSlicer\nG1 X0\n"),
                     "text/plain")}


class TestExportsAuth:
    def test_requires_an_api_key(self, client, key_service, file_service):
        response = client.post("/api/v1/connect/exports", files=_gcode(),
                               data={"metadata": "{}"})
        assert response.status_code == 401
        file_service.upload_files.assert_not_awaited()


class TestExports:
    def test_uploads_the_file_and_returns_the_record(
        self, client, key_service, file_service
    ):
        response = client.post("/api/v1/connect/exports", headers=AUTH,
                               files=_gcode(), data={"metadata": "{}"})

        assert response.status_code == 201
        assert response.json()["data"]["file"] == {
            "file_id": "file-1",
            "filename": "benchy.gcode",
            "file_size": 2841923,
            "file_type": "gcode",
            "checksum": "abc123",
        }
        file_service.upload_files.assert_awaited_once()

    def test_response_never_leaks_the_server_side_file_path(
        self, client, key_service, file_service
    ):
        """Pins the wire contract: named fields only, no filesystem path."""
        response = client.post("/api/v1/connect/exports", headers=AUTH,
                               files=_gcode(), data={"metadata": "{}"})

        file_data = response.json()["data"]["file"]
        assert set(file_data) == {"file_id", "filename", "file_size",
                                  "file_type", "checksum"}
        assert "file_path" not in file_data
        assert "/data/library" not in json.dumps(response.json())

    def test_reports_a_null_checksum_when_the_library_did_not_ingest_the_file(
        self, client, key_service, file_service
    ):
        """
        The checksum comes from the library, which is optional and best-effort
        (FileUploadService.process_file_after_upload swallows its failures), so
        the field is nullable rather than absent.
        """
        file_service.upload_files.return_value = {
            **UPLOAD_OK,
            "uploaded_files": [{**UPLOAD_OK["uploaded_files"][0],
                                "checksum": None}],
        }
        response = client.post("/api/v1/connect/exports", headers=AUTH,
                               files=_gcode(), data={"metadata": "{}"})

        assert response.status_code == 201
        assert response.json()["data"]["file"]["checksum"] is None

    def test_passes_is_business_and_notes_through(
        self, client, key_service, file_service
    ):
        metadata = json.dumps({"is_business": True, "notes": "Order 42"})
        client.post("/api/v1/connect/exports", headers=AUTH,
                    files=_gcode(), data={"metadata": metadata})

        kwargs = file_service.upload_files.await_args.kwargs
        assert kwargs["is_business"] is True
        assert kwargs["notes"] == "Order 42"

    def test_defaults_metadata_when_field_is_absent(
        self, client, key_service, file_service
    ):
        response = client.post("/api/v1/connect/exports", headers=AUTH,
                               files=_gcode())
        assert response.status_code == 201
        assert file_service.upload_files.await_args.kwargs["is_business"] is False

    def test_rejects_unknown_metadata_fields(
        self, client, key_service, file_service
    ):
        metadata = json.dumps({"is_business": True, "print_on": "printer-1"})
        response = client.post("/api/v1/connect/exports", headers=AUTH,
                               files=_gcode(), data={"metadata": metadata})

        assert response.status_code == 422
        file_service.upload_files.assert_not_awaited()

    def test_rejects_malformed_metadata_json(
        self, client, key_service, file_service
    ):
        response = client.post("/api/v1/connect/exports", headers=AUTH,
                               files=_gcode(), data={"metadata": "{not json"})
        assert response.status_code == 422
        file_service.upload_files.assert_not_awaited()

    def test_rejects_an_unsupported_file_type(
        self, client, key_service, file_service
    ):
        response = client.post(
            "/api/v1/connect/exports", headers=AUTH,
            files={"file": ("notes.txt", io.BytesIO(b"hello"), "text/plain")},
            data={"metadata": "{}"},
        )
        assert response.status_code == 422
        file_service.upload_files.assert_not_awaited()

    def test_accepts_bgcode(self, client, key_service, file_service):
        response = client.post(
            "/api/v1/connect/exports", headers=AUTH,
            files={"file": ("benchy.bgcode", io.BytesIO(b"\x00bgcode"),
                            "application/octet-stream")},
            data={"metadata": "{}"},
        )
        assert response.status_code == 201

    def test_returns_400_when_the_upload_fails(
        self, client, key_service, file_service
    ):
        file_service.upload_files.return_value = {
            "uploaded_files": [], "failed_files": [{"filename": "benchy.gcode",
                                                    "error": "duplicate"}],
            "total_count": 1, "success_count": 0, "failure_count": 1,
        }
        response = client.post("/api/v1/connect/exports", headers=AUTH,
                               files=_gcode(), data={"metadata": "{}"})
        assert response.status_code == 400

    def test_returns_403_when_uploads_are_disabled(
        self, client, key_service, file_service
    ):
        file_service.settings.enable_upload = False
        response = client.post("/api/v1/connect/exports", headers=AUTH,
                               files=_gcode(), data={"metadata": "{}"})
        assert response.status_code == 403


class TestUploadValidatorAcceptsBgcode:
    """Guards the real extension gate, which the mocked tests above cannot see."""

    def test_bgcode_is_in_the_allowed_upload_extensions(self):
        from src.utils.config import PrinternizerSettings

        allowed = PrinternizerSettings().allowed_upload_extensions_list
        assert ".bgcode" in allowed, (
            "Core One exports are .bgcode; without this the router accepts the "
            "file and FileUploadService then rejects it as an unsupported type"
        )
